"""
LangGraph research workflow — 10 nodes, sequential with one conditional loop.

Flow:
  intent_parser
    → web_searcher
    → website_scraper
    → data_merger
    → gap_detector ─┐ (if gaps found and retry_count < 2)
    ↑               │
    └─ targeted_researcher
    (else) → insight_extractor
    → report_compiler
    → quality_validator
    → finalizer        (pure state node — worker handles all DB writes)

Web search uses DuckDuckGo's free JSON API (no API key needed).
Website scraping uses httpx + Python's built-in html.parser.
All LLM calls use gpt-4o-mini via langchain_openai.
"""

import json
import re
from html.parser import HTMLParser
from typing import TypedDict

import httpx
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph

from app.config import settings

llm = ChatOpenAI(model="gpt-4o-mini", api_key=settings.openai_api_key, temperature=0)


# ─── State ─────────────────────────────────────────────────────────────────────

class ResearchState(TypedDict):
    # Job inputs
    company_name: str
    company_website: str
    research_objective: str

    # Data collection phase
    search_queries: list[str]      # generated by intent_parser
    search_results: list[str]      # fetched by web_searcher / targeted_researcher
    website_content: str           # scraped by website_scraper
    merged_raw_data: str           # produced by data_merger

    # Insight extraction phase
    company_overview: str
    products_services: str
    target_customers: str
    business_signals: str
    risks_challenges: str
    discovery_questions: list[str]
    outreach_strategy: str
    unknowns: str
    sources: list[str]

    # Control fields
    data_gaps: list[str]           # sections with missing data, from gap_detector
    retry_count: int               # how many targeted-research retries we've done
    quality_passed: bool
    final_report: dict             # fully compiled report, set by report_compiler


# ─── Helpers ───────────────────────────────────────────────────────────────────

class _TextExtractor(HTMLParser):
    """Strip HTML tags — returns only visible text content."""

    _SKIP = {"script", "style", "head", "nav", "footer", "aside", "noscript"}

    def __init__(self) -> None:
        super().__init__()
        self._skipping = False
        self._parts: list[str] = []

    def handle_starttag(self, tag: str, _attrs: list) -> None:
        if tag in self._SKIP:
            self._skipping = True

    def handle_endtag(self, tag: str) -> None:
        if tag in self._SKIP:
            self._skipping = False

    def handle_data(self, data: str) -> None:
        if not self._skipping:
            text = data.strip()
            if text:
                self._parts.append(text)

    def get_text(self) -> str:
        return " ".join(self._parts)


def _ddg_search(query: str) -> str:
    """
    DuckDuckGo Instant Answer API — free, no key required.
    Returns abstract text + related topic snippets for a given query.
    """
    try:
        resp = httpx.get(
            "https://api.duckduckgo.com/",
            params={"q": query, "format": "json", "no_html": "1", "skip_disambig": "1"},
            timeout=10,
            follow_redirects=True,
        )
        data = resp.json()
        parts: list[str] = []
        if data.get("AbstractText"):
            parts.append(data["AbstractText"])
        for topic in data.get("RelatedTopics", [])[:5]:
            if isinstance(topic, dict) and topic.get("Text"):
                parts.append(topic["Text"])
        return "\n".join(parts)
    except Exception:
        return ""  # non-fatal — downstream nodes handle empty results


def _parse_json(content: str, fallback: dict) -> dict:
    """Parse an LLM response as JSON, stripping markdown fences if present."""
    cleaned = re.sub(r"```(?:json)?", "", content).strip("` \n")
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        return fallback


# ─── Nodes ─────────────────────────────────────────────────────────────────────

def intent_parser_node(state: ResearchState) -> dict:
    """
    Parse the research objective and generate targeted search queries.
    Different queries target different report sections so we gather broad data.
    """
    prompt = f"""You are a sales research strategist. Generate 5 specific search queries
to research this company for the given objective.

Company: {state["company_name"]}
Website: {state["company_website"]}
Research Objective: {state["research_objective"]}

Return ONLY valid JSON (no markdown, no extra text):
{{
  "search_queries": [
    "<company name> products services overview",
    "<company name> target customers case studies",
    "<company name> funding news 2024 2025",
    "<company name> competitors market position",
    "<company name> leadership team strategy"
  ]
}}"""

    response = llm.invoke(prompt)
    data = _parse_json(response.content, {
        "search_queries": [
            f"{state['company_name']} company overview products",
            f"{state['company_name']} target customers",
            f"{state['company_name']} funding news recent",
            f"{state['company_name']} competitors market",
            f"{state['company_name']} leadership strategy",
        ]
    })
    return {"search_queries": data.get("search_queries", [])}


def web_searcher_node(state: ResearchState) -> dict:
    """
    Fetch DuckDuckGo instant answers for each search query.
    Appends to existing search_results so targeted_researcher can add to the same list.
    """
    new_results: list[str] = []
    for query in state.get("search_queries", []):
        snippet = _ddg_search(query)
        if snippet:
            new_results.append(f"[Query: {query}]\n{snippet}")

    existing = state.get("search_results", [])
    return {"search_results": existing + new_results}


def website_scraper_node(state: ResearchState) -> dict:
    """
    Fetch the company website and extract visible text.
    Caps at 8 000 chars so we don't blow the LLM context window.
    """
    url = state["company_website"]
    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    try:
        resp = httpx.get(
            url,
            timeout=15,
            follow_redirects=True,
            headers={"User-Agent": "Mozilla/5.0 (compatible; ResearchBot/1.0)"},
        )
        extractor = _TextExtractor()
        extractor.feed(resp.text)
        content = extractor.get_text()[:8000]
    except Exception as exc:
        content = f"[scrape failed: {exc}]"

    return {"website_content": content}


def data_merger_node(state: ResearchState) -> dict:
    """
    Combine website content and search results into a single string.
    Caps at 12 000 chars — enough context for the LLM without excessive tokens.
    """
    parts: list[str] = []

    if state.get("website_content"):
        parts.append(f"=== Company Website ===\n{state['website_content']}")

    if state.get("search_results"):
        parts.append("=== Web Search Results ===\n" + "\n\n".join(state["search_results"]))

    return {"merged_raw_data": "\n\n".join(parts)[:12000]}


def gap_detector_node(state: ResearchState) -> dict:
    """
    Ask the LLM whether the gathered data covers all required report sections.
    Returns a list of section names that lack sufficient data.
    Skips detection if we've already retried twice (avoids infinite loops).
    """
    retry_count = state.get("retry_count", 0)
    if retry_count >= 2:
        return {"data_gaps": [], "retry_count": retry_count}

    prompt = f"""You are checking if research data is sufficient to write a complete company briefing.

Required sections:
1. Company Overview
2. Products & Services
3. Target Customers
4. Business Signals (funding, growth, news)
5. Risks & Challenges

Research data (first 3 000 chars):
{state.get("merged_raw_data", "")[:3000]}

Return ONLY valid JSON:
{{
  "data_gaps": ["section name", ...]
}}

Only list sections with truly NO data. If any information is present, do not flag it."""

    response = llm.invoke(prompt)
    data = _parse_json(response.content, {"data_gaps": []})
    return {"data_gaps": data.get("data_gaps", []), "retry_count": retry_count}


def targeted_researcher_node(state: ResearchState) -> dict:
    """
    Run additional searches targeted at specific data gaps identified by gap_detector.
    Increments retry_count so we don't loop indefinitely.
    """
    gaps = state.get("data_gaps", [])
    new_results: list[str] = []

    for gap in gaps[:3]:  # cap at 3 targeted queries per retry cycle
        query = f"{state['company_name']} {gap}"
        snippet = _ddg_search(query)
        if snippet:
            new_results.append(f"[Targeted — {gap}]\n{snippet}")

    return {
        "search_results": state.get("search_results", []) + new_results,
        "retry_count": state.get("retry_count", 0) + 1,
    }


def insight_extractor_node(state: ResearchState) -> dict:
    """
    Core LLM extraction — reads merged_raw_data and fills all 9 report sections.
    Uses explicit JSON format to ensure reliable structured output.
    """
    prompt = f"""You are a B2B sales research analyst. Extract structured intelligence from the research data below.

Company: {state["company_name"]}
Website: {state["company_website"]}
Research Objective: {state["research_objective"]}

Research Data:
{state.get("merged_raw_data", "")[:6000]}

Return ONLY valid JSON with exactly these keys:
{{
  "company_overview": "2-3 sentence description of what the company does and its market position",
  "products_services": "description of their main products or services",
  "target_customers": "who they sell to — industry, company size, buyer persona",
  "business_signals": "recent funding, growth signals, hiring trends, news",
  "risks_challenges": "key risks or challenges they currently face",
  "discovery_questions": [
    "Specific question 1 tailored to the research objective",
    "Specific question 2",
    "Specific question 3",
    "Specific question 4",
    "Specific question 5"
  ],
  "outreach_strategy": "1-2 sentence recommended approach for first outreach based on the objective",
  "unknowns": "what we could not determine from available data",
  "sources": ["{state["company_website"]}"]
}}

If research data is insufficient for a field, use your knowledge of the company and mark it as (inferred).
Never leave a field empty."""

    response = llm.invoke(prompt)
    fallback = {
        "company_overview": f"{state['company_name']} — details not available (inferred)",
        "products_services": "Not determined from available data",
        "target_customers": "Not determined from available data",
        "business_signals": "No recent signals found",
        "risks_challenges": "Not determined from available data",
        "discovery_questions": [
            "What are your main business challenges right now?",
            "How are you currently handling this problem?",
            "What would success look like in 6 months?",
            "Who else is involved in this decision?",
            "What's your current solution and what's missing?",
        ],
        "outreach_strategy": "Lead with curiosity — ask about their current challenges before pitching.",
        "unknowns": "Most details unavailable due to limited public data.",
        "sources": [state.get("company_website", "")],
    }
    extracted = _parse_json(response.content, fallback)

    return {
        "company_overview": extracted.get("company_overview", fallback["company_overview"]),
        "products_services": extracted.get("products_services", fallback["products_services"]),
        "target_customers": extracted.get("target_customers", fallback["target_customers"]),
        "business_signals": extracted.get("business_signals", fallback["business_signals"]),
        "risks_challenges": extracted.get("risks_challenges", fallback["risks_challenges"]),
        "discovery_questions": extracted.get("discovery_questions", fallback["discovery_questions"]),
        "outreach_strategy": extracted.get("outreach_strategy", fallback["outreach_strategy"]),
        "unknowns": extracted.get("unknowns", fallback["unknowns"]),
        "sources": extracted.get("sources", fallback["sources"]),
    }


def report_compiler_node(state: ResearchState) -> dict:
    """
    Assemble all extracted insights into the final report dict.
    No LLM needed — this is pure data assembly.
    """
    report = {
        "company_overview": state.get("company_overview", ""),
        "products_services": state.get("products_services", ""),
        "target_customers": state.get("target_customers", ""),
        "business_signals": state.get("business_signals", ""),
        "risks_challenges": state.get("risks_challenges", ""),
        "discovery_questions": state.get("discovery_questions", []),
        "outreach_strategy": state.get("outreach_strategy", ""),
        "unknowns": state.get("unknowns", ""),
        "sources": state.get("sources", []),
    }
    return {"final_report": report}


def quality_validator_node(state: ResearchState) -> dict:
    """
    Simple heuristic quality check — passes if at least 5 of 7 key sections
    contain meaningful content (not empty or placeholder text).
    """
    report = state.get("final_report", {})
    key_sections = [
        "company_overview", "products_services", "target_customers",
        "business_signals", "risks_challenges", "outreach_strategy",
        "discovery_questions",
    ]
    filled = sum(
        1 for k in key_sections
        if report.get(k) and report[k] not in ("", [], "Not determined from available data")
    )
    return {"quality_passed": filled >= 4}


def finalizer_node(state: ResearchState) -> dict:
    """
    Terminal node — signals workflow completion.
    All MongoDB writes (reports, session status) are handled by the worker's
    streaming loop AFTER this node completes, keeping nodes side-effect free.
    """
    return {}


# ─── Routing ───────────────────────────────────────────────────────────────────

def _route_after_gap_detection(state: ResearchState) -> str:
    if state.get("data_gaps") and state.get("retry_count", 0) < 2:
        return "targeted_researcher"
    return "insight_extractor"


def _route_after_quality_check(state: ResearchState) -> str:
    # Always finalize — we proceed with what we have even if quality is partial
    return "finalizer"


# ─── Graph assembly ─────────────────────────────────────────────────────────────

def build_research_graph():
    graph = StateGraph(ResearchState)

    graph.add_node("intent_parser", intent_parser_node)
    graph.add_node("web_searcher", web_searcher_node)
    graph.add_node("website_scraper", website_scraper_node)
    graph.add_node("data_merger", data_merger_node)
    graph.add_node("gap_detector", gap_detector_node)
    graph.add_node("targeted_researcher", targeted_researcher_node)
    graph.add_node("insight_extractor", insight_extractor_node)
    graph.add_node("report_compiler", report_compiler_node)
    graph.add_node("quality_validator", quality_validator_node)
    graph.add_node("finalizer", finalizer_node)

    graph.add_edge(START, "intent_parser")
    graph.add_edge("intent_parser", "web_searcher")
    graph.add_edge("web_searcher", "website_scraper")
    graph.add_edge("website_scraper", "data_merger")
    graph.add_edge("data_merger", "gap_detector")
    graph.add_conditional_edges("gap_detector", _route_after_gap_detection)
    graph.add_edge("targeted_researcher", "gap_detector")   # retry loop
    graph.add_edge("insight_extractor", "report_compiler")
    graph.add_edge("report_compiler", "quality_validator")
    graph.add_conditional_edges("quality_validator", _route_after_quality_check)
    graph.add_edge("finalizer", END)

    return graph.compile()


research_graph = build_research_graph()
